spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.10.240:3306/comm_plat
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: ylsk
    ## For more details please see DataSourceProperties.
    hikari:
      maxPoolSize: 5
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

logging:
  register-shutdown-hook: true
  level:
    #org.springframework: info
    com.hazelcast: debug


#程序使用设置 none md5 des aes none表示不使用加密算法
app:
  encryption: md5
  hazelcast:
    url: http://localhost:8200/hazelcast-mancenter
    enable: true
exception:
  message:
    200: 成功
    404: 未找到请求数据
    500: 系统内部异常


